name: Downstream

# Alert downstream repos
on:
  push:
    paths:
      - '**.proto'
      - '**/examples.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger M3O
        run: |
          curl -X POST -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/GWT-M3O-TEST/m3o/dispatches -d '{"event_type":"build_m3o_client"}'
        env:
          GH_PAT: ${{ secrets.API_TOKEN_GITHUB }}
